DATASET:
    DATA_DIR: ""
    NUM_CLASSES: 5
    TEST_FILE_LIST: "./DATA/valM_list.txt"
    TRAIN_FILE_LIST: "./DATA/trainM_list.txt"
    VAL_FILE_LIST: "./DATA/valM_list.txt"
    VIS_FILE_LIST: "./DATA/visM_list.txt"
    IGNORE_INDEX: "255"

MODEL:
    MODEL_NAME: "ddhrnet"
    DEFAULT_NORM_TYPE: "bn"
    HRNET:
        STAGE2:
            NUM_CHANNELS: [64, 128]
        STAGE3:
            NUM_CHANNELS: [64, 128, 256]
        STAGE4:
            NUM_CHANNELS: [64, 128, 256, 512]
TRAIN_CROP_SIZE: (256, 256)
EVAL_CROP_SIZE: (256, 256)
AUG:
    AUG_METHOD: "unpadding"
    FIX_RESIZE_SIZE: (256, 256)
BATCH_SIZE: 4
TRAIN:
    PRETRAINED_MODEL_DIR: ""
    MODEL_SAVE_DIR: "./saved_model/korea_cloud/"
    SNAPSHOT_EPOCH: 1
TEST:
    TEST_MODEL: "./saved_model/korea_cloud/best_model"
SOLVER:
    NUM_EPOCHS: 100
    LR: 0.001
    LR_POLICY: "poly"
    OPTIMIZER: "sgd"

